[package]
name = "topics"
version = "0.1.0"
authors = ["Shane Osbourne <shane.osbourne8@gmail.com>"]
edition = "2018"

[dependencies]
topics_core = {path = "../topics_core", version = "0.1.0"}
env_logger = "0.8.3"
log = "0.4.14"